# thank you for purchasing mStaff PM tinuy#0001 on discord if any questions
# MC-Market: https://www.mc-market.org/members/70883/

license-key: "LICENSE-KEY-HERE"

freeze:
  freeze-usage: "&c/freeze <player>"
  player-not-found: "&cThat player cannot be found!"
  player-unfrozen: "&aYou have been unfrozen!"
  successfully-unfrozen: "&aYou have been unfrozen by &d%player%"
  frozen-player: "&aYou have frozen &d%player%"
  disconnect-command: "ipban %player% 30d Disconnecting whilst frozen -s"
  cannot-do-this: "&cYou cannot do this whilst frozen!"
  frozen-message:
    - "&f████&c█&f████"
    - "&f███&c█&6█&c█&f███ &c&lYou have been frozen!"
    - "&f██&c█&6█&0█&6█&c█&f██"
    - "&f██&c█&6█&0█&6█&c█&f██ &eLogging out will be a ban!"
    - "&f█&c█&6██&0█&6██&c█&f█ &aPlease join our discord"
    - "&f█&c█&6█████&c█&f█"
    - "&c█&6███&0█&6███&c█ &c&nyour.discord.here"
    - "&c█████████"
  disconnected-broadcast:
    - ""
    - "&d%player% %chas disconnected whilst frozen!"
    - ""
  message-delay: 15

staff:
  join-message: "&a+ &d%player% &ehas joined the server!"
  leave-message: "&c- &d%player% &ehas left the server!"

staff-chat:
  enabled: true
  format: "&b[STAFF] &b%player%: &7%msg%"
  no-permission: "&cYou do not have permission to use this command"

mod-messages:
  enabled: "&5Mod Mode: &aEnabled"
  disabled: "&5Mod Mode: &cDisabled"
  cannot-do: "&cYou cannot do this whilst in mod-mode!"
  silently-opening: "&cOpening %block% silently."
  randomly-teleported: "&aYou have been teleported to &b%name%"

mod-mode: # Mod mode settings
  freeze: # Item
    name: "&6Freeze Block" # Item title
    permission: "" # Add a permission to use this item in staff-mode ?
    slot: 8 # What slot should the item be in
    data: 0 # If they item has a meta data (e.g. coloured item), add the meta-data here
    itemId: 174 # Item ID
    fallbackItem: "" # Fallback item if this item doesn't work (e.g. elytra isn't available to a carpet is used)
    action: "FREEZE" # Action to be used
    lore: [] # Item lore
  randomtp:
    name: "&6Random TP"
    permission: ""
    slot: 5
    data: 0
    itemId: 347
    fallbackItem: ""
    action: "RANDOMTP"
    lore: []
  compass:
    name: "&6Teleportation Compass"
    permission: "" # This has the permission worldedit.thru because worldedit will add this item in it's slot regardless of the permission on this item.
    slot: 1
    data: 0
    itemId: 345
    fallbackItem: ""
    action: "UNHANDLED"
    lore: []
  inspector:
    name: "&6Inspection Book"
    permission: ""
    slot: 2
    data: 0
    itemId: 340
    fallbackItem: ""
    action: "INSPECTOR"
    lore: []
  vanish-hidden:
    name: "&6Become Visible"
    permission: ""
    slot: 9
    data: 10
    itemId: 351
    fallbackItem: ""
    action: "VANISH_OFF"
    lore: []
  vanish-visible:
    name: "&6Become Hidden"
    permission: ""
    slot: 9
    data: 8
    itemId: 351
    fallbackItem: ""
    action: "VANISH_ON"
    lore: []